### Simple Zsh Plugins:
### Uncomment these lines after copying the .zsh_plugins
### directory to the home directory (~).
#
# # Define exports used by plugins.
# export DEV_HOME=~/Dev
#
# plugins=(
#     core
#     dev
#     git
#     npm
# )
#
# source ~/.zsh_plugins/simple_zsh_plugins.zsh
# unset plugins

### Uncomment these lines after installing nvm, or delete
### if they were automatically added after installing nvm.
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

### The following items should be kept at the end, i.e., loaded last.

### Uncomment this line after installing Starship.
# eval "$(starship init zsh)"

### Uncomment these line after installing the respective plugins.
# source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
